/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package fr.trandutrieu.remy.springbootjaxws.application.hello;

import javax.jws.WebService;

import fr.trandutrieu.remy.springbootjaxws.application.hello.call.IT568;
import fr.trandutrieu.remy.springbootjaxws.socle.AdapterCall.TYPE_APPEL;
import fr.trandutrieu.remy.springbootjaxws.socle.exceptions.BusinessException;
import fr.trandutrieu.remy.springbootjaxws.socle.webservice.BusinessResponse;
import fr.trandutrieu.remy.springbootjaxws.socle.webservice.WebserviceImpl;

/**
 * Examples code for spring boot with CXF services. HelloPortImpl is the
 * implementation for Hello interface. This class was generated by Apache CXF
 * 3.1.0 2015-05-18T13:02:03.098-05:00 Generated source version: 3.1.0
 */

@WebService
public class HelloPortImpl extends WebserviceImpl implements Hello {
	
    public BusinessResponse sayHello(String myname) {
    	BusinessResponse reponse = new BusinessResponse();
    	reponse.setReponse("Hello, Welcome to CXF Spring boot " + myname + "!!!");
    	return reponse;
    }

    public BusinessResponse sayRuntimeException() {
    	throw new RuntimeException("une erreur grave est survenue");
    }

	@Override
	public BusinessResponse sayBusinessException() throws BusinessException {
    	throw new BusinessException();
	}

	@Override
	public BusinessResponse sayHelloWithExternalCall() throws BusinessException {
		IT568 adapter = new IT568();
		adapter.execute(null, TYPE_APPEL.OK);
    	BusinessResponse reponse = new BusinessResponse();
    	reponse.setReponse(adapter.getClass().getSimpleName() + " " + TYPE_APPEL.OK + "!!!");
		return reponse;
	}
	

	@Override
	public BusinessResponse sayHelloButNullPointer() throws BusinessException {
		IT568 adapter = new IT568();
		adapter.execute(null, TYPE_APPEL.ERREUR_DEV);
    	BusinessResponse reponse = new BusinessResponse();
    	reponse.setReponse("Hello, Welcome to CXF Spring boot " + TYPE_APPEL.ERREUR_DEV + "!!!");
		return reponse;
	}

	@Override
	public BusinessResponse doExternalCallWithTimeOut() throws BusinessException {
		IT568 adapter = new IT568();
		adapter.execute(null, TYPE_APPEL.TIMEOUT);
		throw new UnsupportedOperationException("ne devrait pas passer par ici");
	}

	@Override
	public BusinessResponse doExternalCallWithInterupted() throws BusinessException {
		IT568 adapter = new IT568();
		adapter.execute(null, TYPE_APPEL.EXECUTION_ISSUE);
    	throw new UnsupportedOperationException("ne devrait pas passer par ici");
	}

	@Override
	public BusinessResponse doExternalCallWithExceptionChecked() throws BusinessException {
		IT568 adapter = new IT568();
		adapter.execute(null, TYPE_APPEL.CHECKED_EXCEPTION);
		throw new UnsupportedOperationException("ne devrait pas passer par ici");
	}
    

}
